[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"
default-run = "aoc2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
